### ISSUE TITLE
UI/UX Improvement

### ISSUE THREAD

**Issue by Monu2114** [Soumojitshome2023/nextjs-videocall-webapp#1]
Improving the appearance of the page. 

Assign this task to me

**Comment by Soumojitshome2023** [comment]
Best of luck #gssoc-ext

**Comment by Monu2114** [comment]
Hey can you add these labels as well ? Hacktoberfest-accepted and level2

**Comment by Monu2114** [comment]
dude pls help me out i even emailed you thrice... I didnt mention this in my pr so i didnt get my 25 points. But i mentioned it later. Pls help me out

**Comment by Monu2114** [comment]
> Best of luck #gssoc-ext

heyy pls ? the code is merged but i didnt get my points ?? look into thie pls

**Comment by Monu2114** [comment]
@Soumojitshome2023 heyy my code is merged but i didnt get my score updated can u pls help ?? u did add me label2 right ?
