### ISSUE TITLE
Update Readme.md file

### ISSUE THREAD

**Issue by archanasingh11** [Soumojitshome2023/nextjs-videocall-webapp#11]
**Description:**

The current `README.md` file for the project is outdated and lacks important details that can help new users and contributors better understand the project and get started quickly. Updating the README with clearer and more comprehensive information will improve accessibility and engagement.

Suggested updates include:
- Adding more detailed instructions for installation and setup.
- Expanding on the project overview to include recent updates and features.
- Clarifying the contribution guidelines and linking to the `CONTRIBUTING.md` file.
- Including any additional resources, such as links to documentation or community forums.

Improving the README will make the project more welcoming and easier to navigate for both developers and users.

Please @Soumojitshome2023 assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

**Comment by Soumojitshome2023** [comment]
okay, best of luck

**Comment by archanasingh11** [comment]
Hey @Soumojitshome2023  I have raised the PR
