### ISSUE TITLE
Custom 404 Page for Better User Experience

### ISSUE THREAD

**Issue by myselfshivams** [Soumojitshome2023/nextjs-videocall-webapp#9]
Currently, when users encounter a broken or non-existent link, the website shows the default 404 error page. To enhance the user experience, we should create a custom 404 page with a user-friendly design and helpful navigation options (e.g., a link back to the homepage or other important sections). This will help guide users when they land on a missing page, improving overall usability.

Labels:
- gssoc
- hacktoberfest

@Soumojitshome2023  Please assign this task to me (myselfshivams).

**Comment by Soumojitshome2023** [comment]
best of luck

**Comment by w0wayush** [comment]
Can I work on this PR??

**Comment by Soumojitshome2023** [comment]
Yes

**Comment by myselfshivams** [comment]
@Soumojitshome2023 I have created PR, Please add label of level and assign me.
